### ISSUE TITLE
upfusion 2d looks better than upfusion3d?

### ISSUE THREAD

**Issue by WithFoxSquirrel** [upfusion3d/upfusion#4]
hi, nice work! Visually, upfusion 2d is better than upfusion3d(more sharp), but from the benchmark(PSNR, SSIM,LPIPS), upfusion3d is better

**Comment by thatbrguy** [comment]
Hello, good observation!

Our best guess as to why this is happening is because:
1. Sampling from a generative model (such as UpFusion 2D) provides high fidelity results but will be inconsistent across views, leading to poorer average performance. On the other hand, the consistency of UpFusion 3D enables it to get better metrics across all views. 
2. Reduced visual fidelity of UpFusion 3D is more common for samples in Co3D but not common for clean data (such as GSO and our own self-captured data). We believe this maybe due to the fact that the diffusion model probably has modeled noisy mask artefacts (which are abundant in Co3D) during training and this motivates SDS to converge to a slightly duller solution.

I hope this helps!
